name: Release Theme

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare artifacts
        run: |
          mkdir dist
          cp -v Betterfox/user.js dist/
          cp -rv chrome/ dist/
          tar czvf WaveFox.tar.gz dist/*

      - name: Create GitHub release with assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: commit-${{ github.sha }}
          name: Rolling release
          body: "Automated release for commit ${{ github.sha }}"
          files: |
            WaveFox.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

